version: '3'

services:
  api:
    build: .
    container_name: api
    tty: true
    stdin_open: true
    command: sh
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: database
    ports:
      - 3306:3306
    image: mysql:8.0.32
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    # volumes:
    #   - ./src/database:/docker-entrypoint-initdb.d